# Generated by Django 6.0.2 on 2026-02-24 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0002_exam'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(default='Male', max_length=20),
        ),
        migrations.AlterField(
            model_name='exam',
            name='date',
            field=models.DateField(max_length=40),
        ),
        migrations.AlterField(
            model_name='exam',
            name='exam_code',
            field=models.IntegerField(max_length=40),
        ),
    ]
